/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest known status of every subscribed system.
         * @description Backs the main page: one entry per subscribed feed, carrying the derived traffic-light indicator and enough metadata for a collapsed row. Deliberately takes no parameters and carries no incidents — a card fetches its own detail from /feeds/{feedId}/items when it is expanded.
         */
        get: operations["getOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subscribed feeds. */
        get: operations["listFeeds"];
        put?: never;
        /**
         * Subscribe to a new feed.
         * @description Validates the URL by fetching and parsing it once. Fails with 422 if the URL is unreachable or is not a valid RSS/Atom feed, and 409 if it is already subscribed.
         */
        post: operations["subscribeFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feedId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        /** Get a single feed. */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        /** Unsubscribe from a feed. Cascades to its stored items. */
        delete: operations["deleteFeed"];
        options?: never;
        head?: never;
        /** Update a feed (title, group, cadence, enabled). */
        patch: operations["updateFeed"];
        trace?: never;
    };
    "/feeds/{feedId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        /** List a feed's status items (incidents), newest first. */
        get: operations["listFeedItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feeds/{feedId}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an immediate poll of this feed. */
        post: operations["refreshFeed"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all groups (including the reserved Ungrouped group), by position. */
        get: operations["listGroups"];
        put?: never;
        /** Create a new group. */
        post: operations["createGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group identifier (0 == Ungrouped). */
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        /** Get a single group. */
        get: operations["getGroup"];
        put?: never;
        post?: never;
        /**
         * Delete a group. Its feeds are reparented to Ungrouped.
         * @description The reserved Ungrouped group (id 0) cannot be deleted and returns 400.
         */
        delete: operations["deleteGroup"];
        options?: never;
        head?: never;
        /** Rename or reorder a group. */
        patch: operations["updateGroup"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Normalized, best-effort incident state derived from the feed content. May be "unknown" for feeds that don't follow the Atlassian Statuspage convention.
         * @enum {string}
         */
        Status: "investigating" | "identified" | "monitoring" | "resolved" | "maintenance" | "unknown";
        /**
         * @description The traffic-light shown next to a system, derived server-side from its most recent incident: operational (green), degraded (yellow), outage (red), or unknown (grey — never polled, or the status could not be derived).
         * @enum {string}
         */
        Indicator: "operational" | "degraded" | "outage" | "unknown";
        /** @description One system as the main page needs it: the feed itself plus the derived indicator. Incidents are intentionally absent — see /feeds/{feedId}/items. */
        SystemOverview: {
            feed: components["schemas"]["Feed"];
            indicator: components["schemas"]["Indicator"];
            /**
             * Format: date-time
             * @description Newest incident's timestamp; null when the system has no incidents.
             */
            last_updated_at?: string | null;
        };
        Group: {
            /**
             * Format: int64
             * @description 0 is the reserved, undeletable Ungrouped group.
             * @example 3
             */
            id: number;
            /** @example Dev tools */
            name: string;
            /**
             * @description Display order.
             * @example 0
             */
            position: number;
        };
        Feed: {
            /** Format: int64 */
            id: number;
            /**
             * Format: uri
             * @example https://www.githubstatus.com/history.atom
             */
            url: string;
            /** @example GitHub Status - Incident History */
            title: string;
            /**
             * Format: int64
             * @description 0 == Ungrouped.
             * @default 0
             */
            group_id: number;
            /**
             * @description When false, the feed is not polled.
             * @default true
             */
            enabled: boolean;
            /**
             * @description Poll cadence in seconds.
             * @default 300
             */
            refresh_interval_sec: number;
            /** @description Derived from the most recent incident; null when there are no items. */
            current_status?: components["schemas"]["Status"] | null;
            /**
             * Format: date-time
             * @description Last poll attempt (RFC3339 UTC); null until the first poll.
             */
            last_fetched_at?: string | null;
            /**
             * Format: date-time
             * @description Last successful poll (RFC3339 UTC); null until the first success.
             */
            last_success_at?: string | null;
            /** @description Last failure message; null when healthy. */
            last_error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        StatusItem: {
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            feed_id: number;
            /** @description Stable external id (Atom <id> / RSS <guid> / fallback link). */
            guid: string;
            title: string;
            /**
             * Format: uri
             * @description Permalink to the incident.
             */
            link?: string | null;
            /**
             * Format: date-time
             * @description When the provider published the entry; null for feeds that ship no timestamps (fetched_at is then the only thing we know).
             */
            published_at?: string | null;
            /**
             * Format: date-time
             * @description When the provider last revised the entry; null when it never said.
             */
            updated_at?: string | null;
            /** @description Raw entry body (all updates), preserved verbatim. */
            content_html?: string | null;
            /** @description Stripped plaintext, for preview/search. */
            content_text?: string | null;
            status: components["schemas"]["Status"];
            /** Format: date-time */
            fetched_at: string;
        };
        SubscribeFeedRequest: {
            /**
             * Format: uri
             * @description The RSS/Atom endpoint to subscribe to.
             * @example https://www.githubstatus.com/history.atom
             */
            url: string;
            /** @description Optional display name; defaults to the feed's own <title>. */
            title?: string;
            /**
             * Format: int64
             * @description 0 == Ungrouped. Must reference an existing group.
             * @default 0
             */
            group_id: number;
            /** @default 300 */
            refresh_interval_sec: number;
            /** @default true */
            enabled: boolean;
        };
        /** @description Partial update; omitted fields are left unchanged. */
        UpdateFeedRequest: {
            title?: string;
            /** Format: int64 */
            group_id?: number;
            refresh_interval_sec?: number;
            enabled?: boolean;
        };
        CreateGroupRequest: {
            /** @example Dev tools */
            name: string;
            /** @default 0 */
            position: number;
        };
        /** @description Partial update; omitted fields are left unchanged. */
        UpdateGroupRequest: {
            name?: string;
            position?: number;
        };
        Error: {
            /**
             * @description Stable, machine-readable error code.
             * @example feed_unreachable
             */
            code: string;
            /** @description Human-readable explanation. */
            message: string;
        };
    };
    responses: {
        /** @description The request was malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The resource conflicts with an existing one (e.g. duplicate URL or name). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description The feed URL is unreachable or is not a valid RSS/Atom feed. */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Feed identifier. */
        FeedId: number;
        /** @description Group identifier (0 == Ungrouped). */
        GroupId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per subscribed system. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemOverview"][];
                };
            };
        };
    };
    listFeeds: {
        parameters: {
            query?: {
                /** @description Restrict to feeds in this group (0 == Ungrouped). */
                group_id?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feeds, each with derived current status and health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"][];
                };
            };
        };
    };
    subscribeFeed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeFeedRequest"];
            };
        };
        responses: {
            /** @description The newly created feed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateFeedRequest"];
            };
        };
        responses: {
            /** @description The updated feed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listFeedItems: {
        parameters: {
            query?: {
                /** @description Only items published at or after this RFC3339 timestamp. */
                since?: string;
                /** @description Maximum number of items to return. */
                limit?: number;
            };
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The status items, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusItem"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    refreshFeed: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Feed identifier. */
                feedId: components["parameters"]["FeedId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The feed after the refresh, with updated health fields. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Feed"];
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The groups. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][];
                };
            };
        };
    };
    createGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupRequest"];
            };
        };
        responses: {
            /** @description The newly created group. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    getGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group identifier (0 == Ungrouped). */
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group identifier (0 == Ungrouped). */
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted; member feeds moved to Ungrouped. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    updateGroup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group identifier (0 == Ungrouped). */
                groupId: components["parameters"]["GroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description The updated group. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
}
